const cors={"access-control-allow-origin":"*","access-control-allow-headers":"content-type,x-admin-key","access-control-allow-methods":"GET,POST,OPTIONS"};
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{...cors,"content-type":"application/json;charset=utf-8","cache-control":"no-store"}});
const encode=value=>btoa(String.fromCharCode(...new TextEncoder().encode(value)));
const decode=value=>new TextDecoder().decode(Uint8Array.from(atob(value.replace(/\n/g,"")),c=>c.charCodeAt(0)));
const normalize=links=>{if(!Array.isArray(links)||links.length>100)throw Error("链接数量无效");return links.map((item,index)=>{const label=String(item?.label||"").trim().slice(0,80),url=String(item?.url||"").trim();if(!label||!/^https:\/\/(t\.me|telegram\.me)\/[A-Za-z0-9_+\-/?.=]+$/i.test(url))throw Error(`第 ${index+1} 条链接无效`);return{id:String(item.id||`l_${Date.now()}_${index}`),label,url,active:item.active!==false,sort:index}})};
async function github(env,path,init={}){return fetch(`https://api.github.com/repos/${env.GITHUB_REPO}/contents/${path}`,{...init,headers:{accept:"application/vnd.github+json",authorization:`Bearer ${env.GITHUB_TOKEN}`,"x-github-api-version":"2022-11-28",...(init.headers||{})}})}
async function read(env){const r=await github(env,"data/links.json");if(!r.ok)throw Error("无法读取链接配置");const d=await r.json();return{links:JSON.parse(decode(d.content)),sha:d.sha}}
export async function onRequestOptions(){return new Response(null,{headers:cors})}
export async function onRequestGet({request,env}){if(request.headers.get("x-admin-key")&&request.headers.get("x-admin-key")!==env.ADMIN_TOKEN)return json({error:"未授权"},401);try{const {links}=await read(env);return json({links:normalize(links)})}catch{return json({error:"读取链接失败"},502)}}
export async function onRequestPost({request,env}){if(!env.ADMIN_TOKEN||request.headers.get("x-admin-key")!==env.ADMIN_TOKEN)return json({error:"未授权"},401);try{const body=await request.json(),links=normalize(body.links),current=await read(env),content=encode(JSON.stringify(links,null,2)+"\n");const result=await github(env,"data/links.json",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({message:"update TG URL links via admin",content,sha:current.sha})});if(!result.ok)throw Error();return json({ok:true,links})}catch(error){return json({error:error.message||"保存失败"},400)}}
